
export const metadata = {
  title: "Taxi 8 Support Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="fullSize p-5">
      {children}
    </section>
  );
}
