import Layout from "@/app/_components/Layout/layout";

export const metadata = {
  title: "Taxi 8 Support Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <Layout>{children}</Layout>;
}
