import Layout from "./_components/Layout/layout";
import "./_styles/globals.css";

export const metadata = {
  title: "Taxi 8 Support Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="w-full h-full bg-grayBg" lang="fa">
      <body className="w-full h-full">
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
