import Layout from "./_components/Layout/layout";
import "./_styles/globals.css";
import ThemeRegistry from "@/materialTheme/ThemeRegistry";

export const metadata = {
  title: "Taxi 8 Support Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <ThemeRegistry>

    <html className="fullSize bg-grayBackground " lang="fa">
      <body className="fullSize">
        <Layout>{children}</Layout>
      </body>
    </html>
    </ThemeRegistry>
  );
}
