import Layout from "./_components/Layout/Layout";
import "./_styles/globals.css";

export const metadata = {
  title: "Taxi 8 Support Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="w-full h-full" lang="fa">
      <body className="w-full h-full">
      <Layout>
        {children}
        </Layout>

        </body>
    </html>
  );
}
